### ISSUE TITLE
评估small图片失败

### ISSUE THREAD

**Issue by michaelwanwb** [LinXueyuanStdio/Data-for-LaTeX_OCR#3]
执行评估图片命令:
python evaluate_img.py --results=results/small/
报以下错误
Extra }, or forgotten $

日志显示, 只加载hyp_0.txt文件内公式, hyp_1.txt没有使用, '{'缺少匹配符号'}', 是不是代码bug
Loaded 30 formulas from results/small/formulas_test/hyp_0.txt

**Comment by SuperBoxZero** [comment]
数据集data是不是失效了阿~我这点不开也git submodule updata --init不下来

**Comment by SuperBoxZero** [comment]
可以的话能要个网盘链接嘛5……

**Comment by LinXueyuanStdio** [comment]
@shibo141 
可以下载。git下载失败，请检查网络，可能需要科学上网
本数据永远不会上传网盘。有需求的可以找其他能下载的大佬分享。

@michaelwanwb 
small数据集只是确保模型能跑，但不足以支持模型收敛。
hyp_0.txt里的是模型预测的，此时模型还没有学会letex的语法结构，出错很正常。
